#!/bin/bash

qpid=$(pgrep -f qloop.sh)

if [ "$qpid" != "" ]; then
	if [ "$1" == "stop" ]; then
		kill $qpid
		echo "Queneau loop stopped"
		exit
	fi

	echo "Already running [$qpid]"
	exit
fi

echo "Queneau loop starting. See ./log for output or use \"$0 stop\" to cancel"
nohup "./qloop.sh" $1 $2 $3 >> "./log" 2>&1&
